// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMarkdown(arg1) {
  return window['go']['main']['App']['ExportMarkdown'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveMarkdown(arg1) {
  return window['go']['main']['App']['SaveMarkdown'](arg1);
}
